### ISSUE TITLE
Source port detection should use getresources()

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/seattlelib_v1#126]
The RepyV2 network functions make specifying a source port (and IP address) mandatory. A couple of recent fixes (r6955, r6969) introduced logic to parts of SeattleLib that would search for a source port in the usual vessel port range, 63100-63200. I did not foresee in these patches that we might be using non-standard ports. (The unit tests are one such place where we do that; different clearinghouses might also do their own thing.)

Instead of hardcoding the port range to be searched, we should rather use RepyV2's ```getresources()``` call to get the list of ports that are actually available per the restrictions file.

**Comment by aaaaalbert** [comment]
This is a V2 issue. See SeattleTestbed/seattlelib_v2#126. Closing it for V1.
